# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2bxgRC2XP14yTHoiBLzwJ9BzR1HV55W
"""

import os
import aisuite as ai
import gradio as gr

# 1. API 客戶端設定 (改用環境變數讀取)
# 在 Hugging Face 部署時，我們會在 Settings 設定 GROQ_API_KEY
api_key = os.getenv('GROQ_API_KEY')

# 初始化模型參數
PROVIDER = "groq"
IMAGE_MODEL = "llama-3.1-8b-instant"
TEXT_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"

# 初始化 aisuite 客戶端
try:
    client = ai.Client()
    print("✅ aisuite 客戶端初始化成功。")
except Exception as e:
    client = None
    print(f"❌ 錯誤：aisuite 初始化失敗：{e}")

# 2. Prompt 優化函數 (沿用你的邏輯，但移除 print 診斷以保持介面乾淨)
def optimize_prompt(high_level_concept, ai_type, style, tone):
    if not high_level_concept or high_level_concept.strip() == "":
        return ("### ⚠️ 錯誤：請在「概念輸入」欄位中輸入內容！", "", "")

    if not client or not os.getenv('GROQ_API_KEY'):
        return ("### ❌ 嚴重錯誤：API Key 未設定，請在 Space Settings 中配置 GROQ_API_KEY。", "", "")

    if ai_type == '圖像 (Midjourney/Stable Diffusion)':
        target_model = IMAGE_MODEL
        system_prompt = f"""
        **你是一個世界級的圖像提示詞工程師 (Image Prompt Engineer)。**
        你的任務是將使用者的高層次概念，轉化為一個**結構化、極度詳盡**，且包含專業攝影/藝術術語的單行精準 Prompt。
        **請嚴格遵循以下輸出結構：**
        [主體描述, 動作/表情], [環境/背景, 光線/景深], [藝術風格: {style}, 藝術家], [技術參數, 品質修飾詞]。
        使用者概念: {high_level_concept}
        風格要求: {style}
        """
    elif ai_type == '文字 (GPT-4/Gemini)':
        target_model = TEXT_MODEL
        system_prompt = f"""
        **你是一個專業的內容策劃師和指令優化專家。**
        你的任務是將使用者的高層次概念，優化成一個**結構清晰、目標明確**，能讓目標 LLM 生成一篇高品質內容的指令 Prompt。
        **輸出要求：** 確保 Prompt 指令包含「角色」、「任務」、「格式」和「約束」。
        **風格要求：** {style} 風格。
        **語氣要求：** {tone} 語氣。
        """
    else:
        return ("### ❌ 錯誤：請選擇有效的 AI 輸出類型。", "", "")

    user_concept = f"使用者的高層次概念是：'{high_level_concept}'。請僅輸出最終優化後的 Prompt 文本，不需要任何多餘的解釋或引言。"
    full_model_name = f"{PROVIDER}:{target_model}"

    try:
        messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_concept}]
        response = client.chat.completions.create(
            model=full_model_name,
            messages=messages,
            temperature=0.6
        )
        final_prompt_text = response.choices[0].message.content
        output_html = f"### ✅ 生成完成！🎯 目標模型: **{target_model}**"
        return (output_html, final_prompt_text.strip(), system_prompt.strip())
    except Exception as e:
        return (f"### ❌ API 呼叫失敗！\n錯誤訊息：{str(e)[:100]}", "", "")

# 3. Gradio UI 介面設計
ai_type_options = ['圖像 (Midjourney/Stable Diffusion)', '文字 (GPT-4/Gemini)']

with gr.Blocks(title="智慧型提示詞工程師", theme=gr.themes.Soft()) as demo:
    gr.Markdown("## 🧠 智慧型提示詞工程師 (Intelligent Prompt Engineer)")
    gr.Markdown("此工具利用 **Groq LLM** 的推理能力，將您的「高層次概念」優化成精準 Prompt。")

    with gr.Tab("🚀 Prompt 生成器"):
        with gr.Row():
            with gr.Column(scale=4):
                concept_input = gr.Textbox(label="📝 概念輸入", placeholder="例如: 一隻在遙遠星系旅行的穿著宇航服的貓咪", lines=4)
                ai_type_selector = gr.Dropdown(choices=ai_type_options, value=ai_type_options[0], label="🎯 目標輸出 AI 類型")
                style_selector = gr.Textbox(label="🎨 期望的輸出風格", value="寫實風格 (Photorealistic)")
                tone_selector = gr.Textbox(label="🗣️ 期望的語氣/情緒", value="正式/學術 (Formal/Academic)")
                submit_btn = gr.Button("🚀 生成精準 Prompt", variant="primary")
            with gr.Column(scale=6):
                output_header = gr.HTML(value="### 🎯 優化後的精準 Prompt 將在此處顯示")
                final_prompt_code = gr.Textbox(label="✨ 最終精準 Prompt", lines=8, interactive=False)
                meta_prompt_detail = gr.Code(label="⚙️ 使用的 Meta-Prompt", language="markdown", lines=8, visible=False)
                toggle_meta_btn = gr.Button("顯示/隱藏 Meta-Prompt 專業細節", size="sm")

    submit_btn.click(fn=optimize_prompt, inputs=[concept_input, ai_type_selector, style_selector, tone_selector], outputs=[output_header, final_prompt_code, meta_prompt_detail])

    def toggle_visibility(visible):
        return gr.update(visible=not visible)

    toggle_meta_btn.click(fn=toggle_visibility, inputs=[meta_prompt_detail], outputs=[meta_prompt_detail])

# 4. 啟動服務 (在雲端運行不需 share=True)
if __name__ == "__main__":
    demo.launch()